export interface ExtractedReminder {
  medicationName: string;
  reminderTime: string; // Must strictly follow the "HH:MM" 24h formatting constraint
}

export interface ScheduleExtractionResult {
  remindersFound: ExtractedReminder[];
  confirmationMessage: string; // The contextual text generated by OpenAI
}
